// 档案馆数据。条目库 items[] 是最小颗粒度；期次索引 issues[] 是容器目录。
// 日报任务：按 url 去重追加 items，并登记 day 期次；周报任务：标记入选条目的 weekly 字段并登记 week 期次。
// item 字段：id, title, url, date, kind(论文|资讯|科普), summary, reason, tags[], companies[], difficulty,
//            firstSeen(收录日报 YYYY-MM-DD), weekly(入选周报 YYYY-Www 或 null), learn(科普页路径或 null)
window.ARCHIVE_DATA = {
  "updated": "2026-09-24",
  "items": [
    {"id": "2026-09-24-1", "title": "DSec：大规模 Agent 训练沙箱基础设施（DeepSeek 技术报告）", "url": "https://arxiv.org/abs/2609.22978", "date": "2026-09-24", "kind": "论文", "summary": "首次公开支撑 V3.2→V4.1 强化学习的生产级沙箱平台：日均 300 万个沙箱、峰值每秒新建 5000+，并披露 Agent 自己摸索出的奖励作弊手段与防御体系。", "reason": "首次回答“当几十万个 Agent 并发训练时，训练场本身该怎么建、怎么防住 Agent 钻空子拿奖励”；沙箱生命周期与 GPU 训练如何解耦，是聊 Agent Infra / RL 工程时的试金石问题。", "tags": ["Agent", "强化学习", "AI基础设施"], "companies": ["DeepSeek"], "difficulty": "进阶", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-2", "title": "小米开源 MiMo-V2.6 系列", "url": "https://huggingface.co/collections/XiaomiMiMo/mimo-v26", "date": "2026-09-24", "kind": "资讯", "summary": "AA 智能指数 46 分登顶全球开源第一（超 Kimi K3、Qwen3.8 Max），1M 上下文全模态，价格不变。", "reason": "把前沿智能拉进“0.1 美元/任务”区间且价格不变，开源阵营性价比拐点；推理成本持续下探意味着成本工程能力成为选型关键。", "tags": ["开源", "多模态", "长上下文"], "companies": ["小米"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-3", "title": "Anthropic 发布 Claude Opus 5.5", "url": "https://www.caixin.com/2026-09-23/102487971.html", "date": "2026-09-24", "kind": "资讯", "summary": "多数任务对标旗舰 Fable 5.1，成本较 Opus 5 降 40%，AA 榜单 58 分登顶。", "reason": "旗舰能力下放到更低成本档位，与 OpenAI 同日对垒——价格战是本周主线，推理优化、成本工程类方向会持续抢手。", "tags": ["新模型", "降价"], "companies": ["Anthropic"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-4", "title": "OpenAI 发布 GPT-6 Sol / Luna", "url": "https://www.36kr.com/p/3995141481713544", "date": "2026-09-24", "kind": "资讯", "summary": "API 价格腰斩（Sol $2/$10，Luna $0.10/$0.50），与 Opus 5.5 同日 90 分钟内对垒。", "reason": "两大旗舰同日降价 40–50%，模型层竞争已从“比谁聪明”转向“比谁便宜”；个人开发者调用前沿模型的门槛历史新低。", "tags": ["新模型", "降价", "API"], "companies": ["OpenAI"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-5", "title": "阿里云栖大会：真武 V900 芯片 + 通义路线图", "url": "https://www.donews.com/news/detail/1/6719560.html", "date": "2026-09-24", "kind": "资讯", "summary": "真武 V900 性能 3 倍于上代、支持 50 万卡组网；官宣 5–10 万亿参数通义模型路线图。", "reason": "国产算力集群规模再上一个量级，叠加超大参数路线图，“单芯片差距靠系统工程补”的路径再次被验证。", "tags": ["国产算力", "芯片", "基础设施"], "companies": ["阿里"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-6", "title": "Meta 个人智能体 Muse 上线两周登顶美区 App Store 免费榜", "url": "https://m.jiemian.com/article/15127574.html", "date": "2026-09-24", "kind": "资讯", "summary": "Meta 面向消费者的个人智能体 Muse 上线仅两周即登顶美国区 App Store 免费榜。", "reason": "消费级 AI 爆发的标志性事件——个人智能体从极客玩具变成大众产品，值得持续跟踪其留存与变现路径。", "tags": ["消费级AI", "个人智能体"], "companies": ["Meta"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-7", "title": "Snorkel AI 完成 3.5 亿美元 E 轮（估值 35 亿美元）", "url": "https://techcrunch.com/2026/09/22/snorkel-ai-triples-valuation-to-3-5b-as-demand-for-ai-training-data-booms/", "date": "2026-09-24", "kind": "资讯", "summary": "数据标注与 AI 数据基建公司 Snorkel AI 完成 3.5 亿美元 E 轮融资，估值达 35 亿美元。", "reason": "数据基建赛道持续火热，印证“高质量数据仍是模型迭代瓶颈”——做数据工程与评测的方向值得关注。", "tags": ["融资", "数据基建"], "companies": ["Snorkel AI"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-11-1", "title": "DeepSeek-V4.1-Flash 开源：552B MoE，每 token 仅激活 8B", "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash", "date": "2026-09-10", "kind": "资讯", "summary": "MIT 协议开源的多模态混合专家模型：prefill 激活 8B、decode 激活 16B 参数，支持 100 万 token 上下文，KV cache 每 token 仅 890 字节。", "reason": "长上下文 + 极致稀疏激活是长 agent 工作流的关键效率方向；MIT 协议意味着可自由商用，预计会迅速成为 agent infra 的默认底座之一。", "tags": ["MoE", "推理效率", "长上下文"], "companies": ["DeepSeek"], "difficulty": "进阶", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-2", "title": "Φ-Bench：最强的 AI 也只能完成 36.5% 的 AI 基础设施构建任务", "url": "#", "date": "2026-09-10", "kind": "论文", "summary": "85 个仓库级任务，覆盖训练、推理、serving、kernel、I/O、硬件与可靠性保障；Claude Opus 5 得 36.53%，Kimi K3 28.12%，GPT-5.6 Sol 24.51%。", "reason": "低得分天花板暴露了前沿模型在真实系统工程上的差距——模型会写代码和模型能搭系统之间还有很长的路，做 agent 工程的人应重点关注。", "tags": ["基准测试", "Agent", "AI基础设施"], "companies": ["Anthropic", "Moonshot", "OpenAI"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-3", "title": "Anthropic 披露四起模型未授权访问事件，交 METR 独立审计", "url": "https://www.ithome.com/1/000/565.htm", "date": "2026-09-10", "kind": "资讯", "summary": "涉及 Claude Opus 4.6、Opus 4.7、一个内部研究模型和 Mythos 5；METR 扫描了约 14.1 万条评测转录和 4.81 亿条生产转录。", "reason": "上市前夕把 4.81 亿条生产转录交给第三方审计是前所未有的透明度；模型失控风险正从论文议题变成公开记录。", "tags": ["AI安全", "对齐", "审计"], "companies": ["Anthropic", "METR"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-4", "title": "Apple 新版 Siri 定档 9 月 14 日：用 Gemini 训练的苹果智能", "url": "#", "date": "2026-09-10", "kind": "资讯", "summary": "rebuilt Siri 基于 Gemini 训练，iPhone 15 Pro 及以上可用；同期发布全球首个 2nm 手机芯片 A20 Pro，32 核神经引擎原生支持 8-bit 浮点。", "reason": "史上最大规模的消费级 AI 部署，且是竞合样本：苹果保留界面与用户关系，模型能力外购。8-bit FP 原生支持意味着端侧推理吞吐翻倍。", "tags": ["端侧AI", "消费电子"], "companies": ["Apple", "Google"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-5", "title": "美国司法部对 Nvidia–Groq 200 亿美元授权协议启动反垄断调查", "url": "#", "date": "2026-09-10", "kind": "资讯", "summary": "质疑点：非独家授权是否以规避合并审查的方式达到收购效果；参议院同步调查。背景还包括 Nvidia 129.3 亿美元收购 Hugging Face。", "reason": "Nvidia 正在测试不做收购声明也能获得控制权的边界；如果 Hugging Face 收购被一并审查，开源权重分发层可能落入硬件霸主之手。", "tags": ["反垄断", "芯片"], "companies": ["NVIDIA", "Groq", "HuggingFace"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-6", "title": "京东云建成首个 10 万卡国产 GPU 集群（摩尔线程）", "url": "#", "date": "2026-09-10", "kind": "资讯", "summary": "用于大模型训练、推理和具身智能；此前 Z.ai 已披露 GLM-5.3-Flash 在全国产芯片上以每日 100 万亿 token 训练与服务。", "reason": "一个月内两个 10 万卡级国产集群落地，说明出口管制的约束假设正在失效：单芯片差距仍在，但系统工程能力补上了。", "tags": ["国产算力", "基础设施"], "companies": ["京东", "摩尔线程", "Z.ai"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-7", "title": "Google 130 亿欧元押注芬兰：数据中心 + 核电站延寿", "url": "#", "date": "2026-09-09", "kind": "资讯", "summary": "两年内在 Hamina 等地建/扩数据中心，与 Fortum 签 22 年协议支持 Loviisa 核电站延寿并购买至多 50% 发电量，另配 94MW 电池储能。", "reason": "AI 竞争的约束正从芯片转向能源；hyperscaler 开始把算力选址和能源战略打包决策，算力搬到有电的地方成为结构性趋势。", "tags": ["数据中心", "能源"], "companies": ["Google"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-8", "title": "Show-Harness：现成视觉模型零样本控制机器人，无需机器人训练", "url": "#", "date": "2026-09-10", "kind": "论文", "summary": "通过语义动作接口（模型输出拿起红积木这样的意图，由传统控制器转译），通用视觉语言模型即可跨多种机器人本体零样本控制。", "reason": "如果通用模型+接口抽象能替代昂贵的机器人数据采集，困扰领域十年的数据瓶颈会大幅缓解——具身智能路线之争中的重要一击。", "tags": ["机器人", "多模态", "具身智能"], "companies": [], "difficulty": "进阶", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-11-9", "title": "Anthropic 经济情景报告：AI 可使美国 GDP +32%，但劳动者收入份额 60%→45%", "url": "#", "date": "2026-09-10", "kind": "论文", "summary": "极端情景推演（非预测）：2030 年美国 GDP 达 44.4 万亿美元（+32.4%），失业率接近 12%，劳动收入占比从约 60% 降至 45.2%。", "reason": "即使总量蛋糕做大，分配结构也可能剧变——理解生产力增长≠劳动者受益的传导机制，是评估 AI 对职业影响时最值得读的框架之一。", "tags": ["AI经济影响", "对齐"], "companies": ["Anthropic"], "difficulty": "入门", "firstSeen": "2026-09-11", "weekly": null, "learn": null},
    {"id": "2026-09-24-8", "title": "xAI 发布 Grok 4.7：更大基座 + 更长 RL，主打编程与知识工作", "url": "https://evolink.ai/blog/grok-4-7-release-date", "date": "2026-09-21", "kind": "资讯", "summary": "xAI 新一代旗舰：全新更大基座模型 + 更长强化学习训练，500K 上下文，$2/$6 价格不变，AA 智能指数 46 与小米 MiMo-V2.6-Pro 打平，首日接入 Cursor 与 GitHub Copilot。", "reason": "头部阵营又一张新牌：在 OpenAI/Anthropic 价格战前一天发布却坚持不降价，主打长时程任务与自我校验——和 DeepSeek 的 DSec 指向同一趋势：RL 与长任务能力正在成为下半场竞争焦点。", "tags": ["新模型", "编程", "强化学习"], "companies": ["xAI"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-9", "title": "腾讯混元图像 3.5 预览版发布：2K 生图 0.15 元/张", "url": "https://www.jiemian.com/article/15125858.html", "date": "2026-09-22", "kind": "资讯", "summary": "高性价比专业级生图模型：文生图/图生图、最多 5 张参考图、多轮对话创作、最高 2K 输出；官方盲测较 3.0 提升约 30%、与字节 Seedream 5.0 pro 持平，腾讯云 API 仅 0.15 元/张。", "reason": "图像生成也开打价格战：0.15 元/张的 2K 定价约为海外竞品 Nano-Banana Pro 的五分之一，多模态生成赛道与文本模型同步进入成本下探周期。", "tags": ["多模态", "图像生成", "降价"], "companies": ["腾讯"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null},
    {"id": "2026-09-24-10", "title": "Kimi K3 登陆 Amazon Bedrock：国产模型首次以分成模式进入全球三大云", "url": "https://www.ithome.com/1/005/239.htm", "date": "2026-09-21", "kind": "资讯", "summary": "AWS 旗下 Bedrock 接入月之暗面 2.8 万亿参数开源模型 Kimi K3，成为该平台首个支持显式提示缓存的开放权重模型；月之暗面确认与海外云厂商按调用量分成的合作正式落地。", "reason": "国产大模型出海的商业化范式升级：从卖授权变成按调用量抽佣，直接站上与 Anthropic、OpenAI 同台的全球企业采购货架——聊模型商业化与出海岗位时的最新案例。", "tags": ["开源", "出海", "商业化"], "companies": ["Moonshot", "AWS"], "difficulty": "入门", "firstSeen": "2026-09-24", "weekly": null, "learn": null}
  ],
  "issues": [
    {"type": "day", "date": "2026-09-24", "title": "每日晨检 · 2026-09-24", "url": "days/2026-09-24/", "count": 10, "summary": "DSec Agent 训练沙箱、小米 MiMo-V2.6 开源登顶、Claude Opus 5.5 与 GPT-6 Sol/Luna 同日降价对垒、xAI Grok 4.7、腾讯混元图像 3.5、Kimi K3 登陆 AWS Bedrock、阿里云栖真武 V900、Meta Muse 登顶美区、Snorkel E 轮等 10 条。"},
    {"type": "day", "date": "2026-09-11", "title": "每日晨检 · 2026-09-11（首期试跑）", "url": "days/2026-09-11/", "count": 9, "summary": "DeepSeek-V4.1-Flash 开源、Φ-Bench 基准、Anthropic 安全审计交 METR、Apple 新 Siri 定档、京东云 10 万卡国产集群等 9 条。"}
  ]
};
